### PR TITLE
Fixing deprecation message of Rails 3.1.1

### PR DESCRIPTION
**Pull request by maksar**
DEPRECATION WARNING: primary_key_name is deprecated and will be removed from Rails 3.2 (use foreign_key instead). (called from reflection_foreign_key at /Users/maksar/.rvm/gems/ruby-1.9.3-p0@tc_portal/gems/remarkable_activerecord-4.0.0.alpha4/lib/remarkable/active_record/matchers/association_matcher.rb:97)

### CODE REVIEW

**Comment by hosh** [comment]
@maksar thanks for the pull request.

I'm trying to think if someone's already made this pull request and I've merged it into a non-master branch. If not, I'll merge this ine.

**Comment by maksar** [comment]
Actually, I've found, that on https://github.com/remarkable/remarkable in rails-3.1 branch all needed changes was already made. Unfortunately, they are not hurrying to make release from this branch. So, you can just merge with upstream and release. That's exactly what I did (gem "maksar-remarkable_activerecord", "~> 4.0.0.alpha6"), it's release from (remarkable/remarkable) repository, without your commits :(

**Comment by hosh** [comment]
@maksar I appreciate it. I've been having my head with my employer's work and this has been admittedly at the bottom of my priority list.

**Comment by joaomilho** [comment]
Just a feedback: Had this issue too with AR3.2.1. maksar's gem worked fine.

**Pull request closed without merging**
